// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: luqchain/bridge/multistore.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// _______________________[AppHash]______________
// /                                              \
// _________________[I19]_________________                         ____[I20*]____
// /                                       \	                      /              \
// _______[I15*]______                       _______[I16]_________        [GHIJ]           [KLMN]
// /                   \                     /                     \
// __[I8]__              __[I9]__            __[I10*]__             __[I11]__
// /        \            /         \         /          \           /         \
// [I0]      [I1]       [I2]        [I3]     [I4]         [I5]      [I6*]       [I7]
// /  \     /   \      /   \      /    \    /    \        /  \      /   \      /   \
// [0] [1]  [2]   [3]  [4]  [5]  [6]    [7] [8]   [9]     [A] [B]   [C]  [D]  [E*]  [F*]
// Right[F], Left[I6], Left[I10], Left[I15], Right[I20]
// [0] - acc (auth)     [1] - authz     [2] - bank      [3] - capability [4] - consensus [5] - crisis
// [6] - distr          [7] - evidence  [8] - feegrant  [9] - gov        [A] - group     [B] - ibc
// [C] - icacontroller  [D] - icahost   [E] - luqchain  [F] - mint       [G] - params    [H] - slashing
// [I] - staking        [J] - transfer  [K] - upgrade   [L] - vesting
type MultiStoreTreeFields struct {
	LuqchainIavlStateHash            []byte `protobuf:"bytes,1,opt,name=luqchain_iavl_state_hash,json=luqchainIavlStateHash,proto3" json:"luqchain_iavl_state_hash,omitempty"`
	MintStoreMerkleHash              []byte `protobuf:"bytes,2,opt,name=mint_store_merkle_hash,json=mintStoreMerkleHash,proto3" json:"mint_store_merkle_hash,omitempty"`
	IcacontrollerToIcahostMerkleHash []byte `protobuf:"bytes,3,opt,name=icacontroller_to_icahost_merkle_hash,json=icacontrollerToIcahostMerkleHash,proto3" json:"icacontroller_to_icahost_merkle_hash,omitempty"`
	FeegrantToIbcMerkleHash          []byte `protobuf:"bytes,4,opt,name=feegrant_to_ibc_merkle_hash,json=feegrantToIbcMerkleHash,proto3" json:"feegrant_to_ibc_merkle_hash,omitempty"`
	AccToEvidenceMerkleHash          []byte `protobuf:"bytes,5,opt,name=acc_to_evidence_merkle_hash,json=accToEvidenceMerkleHash,proto3" json:"acc_to_evidence_merkle_hash,omitempty"`
	ParamsToVestingMerkleHash        []byte `protobuf:"bytes,6,opt,name=params_to_vesting_merkle_hash,json=paramsToVestingMerkleHash,proto3" json:"params_to_vesting_merkle_hash,omitempty"`
}

func (m *MultiStoreTreeFields) Reset()         { *m = MultiStoreTreeFields{} }
func (m *MultiStoreTreeFields) String() string { return proto.CompactTextString(m) }
func (*MultiStoreTreeFields) ProtoMessage()    {}
func (*MultiStoreTreeFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_f573ebd55744e127, []int{0}
}
func (m *MultiStoreTreeFields) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MultiStoreTreeFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MultiStoreTreeFields.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MultiStoreTreeFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiStoreTreeFields.Merge(m, src)
}
func (m *MultiStoreTreeFields) XXX_Size() int {
	return m.Size()
}
func (m *MultiStoreTreeFields) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiStoreTreeFields.DiscardUnknown(m)
}

var xxx_messageInfo_MultiStoreTreeFields proto.InternalMessageInfo

func (m *MultiStoreTreeFields) GetLuqchainIavlStateHash() []byte {
	if m != nil {
		return m.LuqchainIavlStateHash
	}
	return nil
}

func (m *MultiStoreTreeFields) GetMintStoreMerkleHash() []byte {
	if m != nil {
		return m.MintStoreMerkleHash
	}
	return nil
}

func (m *MultiStoreTreeFields) GetIcacontrollerToIcahostMerkleHash() []byte {
	if m != nil {
		return m.IcacontrollerToIcahostMerkleHash
	}
	return nil
}

func (m *MultiStoreTreeFields) GetFeegrantToIbcMerkleHash() []byte {
	if m != nil {
		return m.FeegrantToIbcMerkleHash
	}
	return nil
}

func (m *MultiStoreTreeFields) GetAccToEvidenceMerkleHash() []byte {
	if m != nil {
		return m.AccToEvidenceMerkleHash
	}
	return nil
}

func (m *MultiStoreTreeFields) GetParamsToVestingMerkleHash() []byte {
	if m != nil {
		return m.ParamsToVestingMerkleHash
	}
	return nil
}

type IAVLMerklePath struct {
	IsDataOnRight  bool   `protobuf:"varint,1,opt,name=is_data_on_right,json=isDataOnRight,proto3" json:"is_data_on_right,omitempty"`
	SubtreeHeight  uint32 `protobuf:"varint,2,opt,name=subtree_height,json=subtreeHeight,proto3" json:"subtree_height,omitempty"`
	SubtreeSize    uint64 `protobuf:"varint,3,opt,name=subtree_size,json=subtreeSize,proto3" json:"subtree_size,omitempty"`
	SubtreeVersion uint64 `protobuf:"varint,4,opt,name=subtree_version,json=subtreeVersion,proto3" json:"subtree_version,omitempty"`
	SiblingHash    []byte `protobuf:"bytes,5,opt,name=sibling_hash,json=siblingHash,proto3" json:"sibling_hash,omitempty"`
}

func (m *IAVLMerklePath) Reset()         { *m = IAVLMerklePath{} }
func (m *IAVLMerklePath) String() string { return proto.CompactTextString(m) }
func (*IAVLMerklePath) ProtoMessage()    {}
func (*IAVLMerklePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f573ebd55744e127, []int{1}
}
func (m *IAVLMerklePath) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IAVLMerklePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IAVLMerklePath.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IAVLMerklePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IAVLMerklePath.Merge(m, src)
}
func (m *IAVLMerklePath) XXX_Size() int {
	return m.Size()
}
func (m *IAVLMerklePath) XXX_DiscardUnknown() {
	xxx_messageInfo_IAVLMerklePath.DiscardUnknown(m)
}

var xxx_messageInfo_IAVLMerklePath proto.InternalMessageInfo

func (m *IAVLMerklePath) GetIsDataOnRight() bool {
	if m != nil {
		return m.IsDataOnRight
	}
	return false
}

func (m *IAVLMerklePath) GetSubtreeHeight() uint32 {
	if m != nil {
		return m.SubtreeHeight
	}
	return 0
}

func (m *IAVLMerklePath) GetSubtreeSize() uint64 {
	if m != nil {
		return m.SubtreeSize
	}
	return 0
}

func (m *IAVLMerklePath) GetSubtreeVersion() uint64 {
	if m != nil {
		return m.SubtreeVersion
	}
	return 0
}

func (m *IAVLMerklePath) GetSiblingHash() []byte {
	if m != nil {
		return m.SiblingHash
	}
	return nil
}

func init() {
	proto.RegisterType((*MultiStoreTreeFields)(nil), "luqchain.bridge.MultiStoreTreeFields")
	proto.RegisterType((*IAVLMerklePath)(nil), "luqchain.bridge.IAVLMerklePath")
}

func init() { proto.RegisterFile("luqchain/bridge/multistore.proto", fileDescriptor_f573ebd55744e127) }

var fileDescriptor_f573ebd55744e127 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x63, 0x1a, 0x2a, 0xb4, 0x6d, 0x5a, 0x64, 0x28, 0x14, 0x21, 0xac, 0x50, 0x81, 0xca,
	0xa9, 0x39, 0xf4, 0xc0, 0x85, 0x03, 0x20, 0x40, 0x8d, 0x44, 0x01, 0x39, 0x56, 0x0e, 0x5c, 0x56,
	0xe3, 0xcd, 0x10, 0xaf, 0x58, 0xef, 0x86, 0xdd, 0x89, 0x25, 0xfa, 0x2b, 0x10, 0xbf, 0x8a, 0x1b,
	0x39, 0x72, 0x44, 0xc9, 0x1f, 0x41, 0xbb, 0xb6, 0x45, 0xdc, 0xeb, 0x9b, 0xef, 0xbd, 0xd1, 0xbc,
	0x5d, 0x36, 0x54, 0xcb, 0x6f, 0xa2, 0x00, 0xa9, 0x47, 0xb9, 0x95, 0xb3, 0x39, 0x8e, 0xca, 0xa5,
	0x22, 0xe9, 0xc8, 0x58, 0x3c, 0x5b, 0x58, 0x43, 0x26, 0x3e, 0x6c, 0x89, 0xb3, 0x9a, 0x38, 0xf9,
	0xb9, 0xc3, 0xee, 0x5e, 0x7a, 0x6a, 0xe2, 0xa9, 0xcc, 0x22, 0xbe, 0x93, 0xa8, 0x66, 0x2e, 0x7e,
	0xce, 0x8e, 0x5b, 0x96, 0x4b, 0xa8, 0x14, 0x77, 0x04, 0x84, 0xbc, 0x00, 0x57, 0x1c, 0x47, 0xc3,
	0xe8, 0xd9, 0x7e, 0x7a, 0xd4, 0xce, 0xc7, 0x50, 0xa9, 0x89, 0x9f, 0x5e, 0x80, 0x2b, 0xe2, 0x73,
	0x76, 0xaf, 0x94, 0x9a, 0x78, 0x58, 0xcb, 0x4b, 0xb4, 0x5f, 0x55, 0x63, 0xbb, 0x11, 0x6c, 0x77,
	0xfc, 0x34, 0x6c, 0xbb, 0x0c, 0xb3, 0x60, 0xfa, 0xc0, 0x9e, 0x48, 0x01, 0xc2, 0x68, 0xb2, 0x46,
	0x29, 0xb4, 0x9c, 0x0c, 0x97, 0x02, 0x0a, 0xe3, 0xa8, 0x13, 0xb1, 0x13, 0x22, 0x86, 0x1d, 0x36,
	0x33, 0xe3, 0x9a, 0xdc, 0xca, 0x7b, 0xc1, 0x1e, 0x7e, 0x41, 0x9c, 0x5b, 0xd0, 0x14, 0xa2, 0x72,
	0xd1, 0x89, 0xe9, 0x87, 0x98, 0xfb, 0x2d, 0x92, 0x99, 0x71, 0x2e, 0xba, 0x6e, 0x10, 0xc2, 0x1b,
	0xb1, 0x92, 0x33, 0xd4, 0xa2, 0x7b, 0xc7, 0xcd, 0xda, 0x0d, 0x42, 0x64, 0xe6, 0x6d, 0x03, 0x6c,
	0xb9, 0x5f, 0xb2, 0x47, 0x0b, 0xb0, 0x50, 0x3a, 0x1f, 0x50, 0xa1, 0x23, 0xa9, 0xe7, 0x1d, 0xff,
	0x6e, 0xf0, 0x3f, 0xa8, 0xa1, 0xcc, 0x4c, 0x6b, 0xe4, 0x7f, 0xc2, 0xc9, 0xef, 0x88, 0x1d, 0x8c,
	0x5f, 0x4d, 0xdf, 0xd7, 0xd2, 0x27, 0xa0, 0x22, 0x3e, 0x65, 0xb7, 0xa5, 0xe3, 0x33, 0x20, 0xe0,
	0x46, 0x73, 0x2b, 0xe7, 0x05, 0x85, 0x67, 0xb8, 0x95, 0x0e, 0xa4, 0x7b, 0x03, 0x04, 0x1f, 0x75,
	0xea, 0xc5, 0xf8, 0x29, 0x3b, 0x70, 0xcb, 0x9c, 0x2c, 0x22, 0x2f, 0x30, 0x60, 0xbe, 0xf6, 0x41,
	0x3a, 0x68, 0xd4, 0x8b, 0x20, 0xc6, 0x8f, 0xd9, 0x7e, 0x8b, 0x39, 0x79, 0x85, 0xa1, 0xd8, 0x7e,
	0xba, 0xd7, 0x68, 0x13, 0x79, 0x85, 0xf1, 0x29, 0x3b, 0x6c, 0x91, 0x0a, 0xad, 0x93, 0x46, 0x87,
	0xde, 0xfa, 0x69, 0xbb, 0x60, 0x5a, 0xab, 0x21, 0x4b, 0xe6, 0xca, 0x9f, 0xb9, 0xd5, 0xcf, 0x5e,
	0xa3, 0xf9, 0x8b, 0x5e, 0x8f, 0x7e, 0xad, 0x93, 0x68, 0xb5, 0x4e, 0xa2, 0xbf, 0xeb, 0x24, 0xfa,
	0xb1, 0x49, 0x7a, 0xab, 0x4d, 0xd2, 0xfb, 0xb3, 0x49, 0x7a, 0x9f, 0x8f, 0xae, 0xff, 0x59, 0xfa,
	0xbe, 0x40, 0x97, 0xef, 0x86, 0xff, 0x7a, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x62, 0x0a, 0xbb,
	0xfd, 0xd3, 0x02, 0x00, 0x00,
}

func (m *MultiStoreTreeFields) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MultiStoreTreeFields) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MultiStoreTreeFields) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParamsToVestingMerkleHash) > 0 {
		i -= len(m.ParamsToVestingMerkleHash)
		copy(dAtA[i:], m.ParamsToVestingMerkleHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.ParamsToVestingMerkleHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AccToEvidenceMerkleHash) > 0 {
		i -= len(m.AccToEvidenceMerkleHash)
		copy(dAtA[i:], m.AccToEvidenceMerkleHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.AccToEvidenceMerkleHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FeegrantToIbcMerkleHash) > 0 {
		i -= len(m.FeegrantToIbcMerkleHash)
		copy(dAtA[i:], m.FeegrantToIbcMerkleHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.FeegrantToIbcMerkleHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.IcacontrollerToIcahostMerkleHash) > 0 {
		i -= len(m.IcacontrollerToIcahostMerkleHash)
		copy(dAtA[i:], m.IcacontrollerToIcahostMerkleHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.IcacontrollerToIcahostMerkleHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MintStoreMerkleHash) > 0 {
		i -= len(m.MintStoreMerkleHash)
		copy(dAtA[i:], m.MintStoreMerkleHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.MintStoreMerkleHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.LuqchainIavlStateHash) > 0 {
		i -= len(m.LuqchainIavlStateHash)
		copy(dAtA[i:], m.LuqchainIavlStateHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.LuqchainIavlStateHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IAVLMerklePath) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IAVLMerklePath) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IAVLMerklePath) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SiblingHash) > 0 {
		i -= len(m.SiblingHash)
		copy(dAtA[i:], m.SiblingHash)
		i = encodeVarintMultistore(dAtA, i, uint64(len(m.SiblingHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SubtreeVersion != 0 {
		i = encodeVarintMultistore(dAtA, i, uint64(m.SubtreeVersion))
		i--
		dAtA[i] = 0x20
	}
	if m.SubtreeSize != 0 {
		i = encodeVarintMultistore(dAtA, i, uint64(m.SubtreeSize))
		i--
		dAtA[i] = 0x18
	}
	if m.SubtreeHeight != 0 {
		i = encodeVarintMultistore(dAtA, i, uint64(m.SubtreeHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.IsDataOnRight {
		i--
		if m.IsDataOnRight {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMultistore(dAtA []byte, offset int, v uint64) int {
	offset -= sovMultistore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MultiStoreTreeFields) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LuqchainIavlStateHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	l = len(m.MintStoreMerkleHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	l = len(m.IcacontrollerToIcahostMerkleHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	l = len(m.FeegrantToIbcMerkleHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	l = len(m.AccToEvidenceMerkleHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	l = len(m.ParamsToVestingMerkleHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	return n
}

func (m *IAVLMerklePath) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsDataOnRight {
		n += 2
	}
	if m.SubtreeHeight != 0 {
		n += 1 + sovMultistore(uint64(m.SubtreeHeight))
	}
	if m.SubtreeSize != 0 {
		n += 1 + sovMultistore(uint64(m.SubtreeSize))
	}
	if m.SubtreeVersion != 0 {
		n += 1 + sovMultistore(uint64(m.SubtreeVersion))
	}
	l = len(m.SiblingHash)
	if l > 0 {
		n += 1 + l + sovMultistore(uint64(l))
	}
	return n
}

func sovMultistore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMultistore(x uint64) (n int) {
	return sovMultistore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MultiStoreTreeFields) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultistore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MultiStoreTreeFields: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MultiStoreTreeFields: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LuqchainIavlStateHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LuqchainIavlStateHash = append(m.LuqchainIavlStateHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LuqchainIavlStateHash == nil {
				m.LuqchainIavlStateHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintStoreMerkleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintStoreMerkleHash = append(m.MintStoreMerkleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MintStoreMerkleHash == nil {
				m.MintStoreMerkleHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IcacontrollerToIcahostMerkleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IcacontrollerToIcahostMerkleHash = append(m.IcacontrollerToIcahostMerkleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.IcacontrollerToIcahostMerkleHash == nil {
				m.IcacontrollerToIcahostMerkleHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeegrantToIbcMerkleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeegrantToIbcMerkleHash = append(m.FeegrantToIbcMerkleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.FeegrantToIbcMerkleHash == nil {
				m.FeegrantToIbcMerkleHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccToEvidenceMerkleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccToEvidenceMerkleHash = append(m.AccToEvidenceMerkleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.AccToEvidenceMerkleHash == nil {
				m.AccToEvidenceMerkleHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamsToVestingMerkleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParamsToVestingMerkleHash = append(m.ParamsToVestingMerkleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ParamsToVestingMerkleHash == nil {
				m.ParamsToVestingMerkleHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMultistore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultistore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IAVLMerklePath) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMultistore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IAVLMerklePath: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IAVLMerklePath: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDataOnRight", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDataOnRight = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubtreeHeight", wireType)
			}
			m.SubtreeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubtreeHeight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubtreeSize", wireType)
			}
			m.SubtreeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubtreeSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubtreeVersion", wireType)
			}
			m.SubtreeVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubtreeVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SiblingHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMultistore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMultistore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SiblingHash = append(m.SiblingHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SiblingHash == nil {
				m.SiblingHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMultistore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMultistore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMultistore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMultistore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMultistore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMultistore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMultistore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMultistore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMultistore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMultistore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMultistore = fmt.Errorf("proto: unexpected end of group")
)
