// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: luqchain/bridge/services.proto

package bridge

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryBlockheaderMerkleRequest is request type for the Query/QueryBlockheaderMerkleRequest RPC method.
type QueryBlockheaderMerkleRequest struct {
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryBlockheaderMerkleRequest) Reset()         { *m = QueryBlockheaderMerkleRequest{} }
func (m *QueryBlockheaderMerkleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBlockheaderMerkleRequest) ProtoMessage()    {}
func (*QueryBlockheaderMerkleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{0}
}
func (m *QueryBlockheaderMerkleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBlockheaderMerkleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBlockheaderMerkleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBlockheaderMerkleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlockheaderMerkleRequest.Merge(m, src)
}
func (m *QueryBlockheaderMerkleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBlockheaderMerkleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlockheaderMerkleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlockheaderMerkleRequest proto.InternalMessageInfo

func (m *QueryBlockheaderMerkleRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type QueryBlockheaderMerkleResponse struct {
	BlockheaderMerkle BlockHeaderMerkle `protobuf:"bytes,1,opt,name=blockheaderMerkle,proto3" json:"blockheaderMerkle"`
}

func (m *QueryBlockheaderMerkleResponse) Reset()         { *m = QueryBlockheaderMerkleResponse{} }
func (m *QueryBlockheaderMerkleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBlockheaderMerkleResponse) ProtoMessage()    {}
func (*QueryBlockheaderMerkleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{1}
}
func (m *QueryBlockheaderMerkleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBlockheaderMerkleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBlockheaderMerkleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBlockheaderMerkleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlockheaderMerkleResponse.Merge(m, src)
}
func (m *QueryBlockheaderMerkleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBlockheaderMerkleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlockheaderMerkleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlockheaderMerkleResponse proto.InternalMessageInfo

func (m *QueryBlockheaderMerkleResponse) GetBlockheaderMerkle() BlockHeaderMerkle {
	if m != nil {
		return m.BlockheaderMerkle
	}
	return BlockHeaderMerkle{}
}

type QueryBlockheaderMerkleEVMResponse struct {
	BlockheaderMerkleEvm BlockHeaderMerkleEvm `protobuf:"bytes,1,opt,name=blockheaderMerkleEvm,proto3" json:"blockheaderMerkleEvm"`
}

func (m *QueryBlockheaderMerkleEVMResponse) Reset()         { *m = QueryBlockheaderMerkleEVMResponse{} }
func (m *QueryBlockheaderMerkleEVMResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBlockheaderMerkleEVMResponse) ProtoMessage()    {}
func (*QueryBlockheaderMerkleEVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{2}
}
func (m *QueryBlockheaderMerkleEVMResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBlockheaderMerkleEVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBlockheaderMerkleEVMResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBlockheaderMerkleEVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlockheaderMerkleEVMResponse.Merge(m, src)
}
func (m *QueryBlockheaderMerkleEVMResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBlockheaderMerkleEVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlockheaderMerkleEVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlockheaderMerkleEVMResponse proto.InternalMessageInfo

func (m *QueryBlockheaderMerkleEVMResponse) GetBlockheaderMerkleEvm() BlockHeaderMerkleEvm {
	if m != nil {
		return m.BlockheaderMerkleEvm
	}
	return BlockHeaderMerkleEvm{}
}

type QueryMultistoreRequest struct {
	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Qid       string `protobuf:"bytes,2,opt,name=qid,proto3" json:"qid,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *QueryMultistoreRequest) Reset()         { *m = QueryMultistoreRequest{} }
func (m *QueryMultistoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMultistoreRequest) ProtoMessage()    {}
func (*QueryMultistoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{3}
}
func (m *QueryMultistoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultistoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultistoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultistoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultistoreRequest.Merge(m, src)
}
func (m *QueryMultistoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultistoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultistoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultistoreRequest proto.InternalMessageInfo

func (m *QueryMultistoreRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *QueryMultistoreRequest) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func (m *QueryMultistoreRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type QueryMultistoreResponse struct {
	MutiStoreTree MutiStoreTreeFields `protobuf:"bytes,1,opt,name=MutiStoreTree,proto3" json:"MutiStoreTree"`
	Iavl          []IAVLMerklePathEvm `protobuf:"bytes,2,rep,name=iavl,proto3" json:"iavl"`
}

func (m *QueryMultistoreResponse) Reset()         { *m = QueryMultistoreResponse{} }
func (m *QueryMultistoreResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMultistoreResponse) ProtoMessage()    {}
func (*QueryMultistoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{4}
}
func (m *QueryMultistoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMultistoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMultistoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMultistoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMultistoreResponse.Merge(m, src)
}
func (m *QueryMultistoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMultistoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMultistoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMultistoreResponse proto.InternalMessageInfo

func (m *QueryMultistoreResponse) GetMutiStoreTree() MutiStoreTreeFields {
	if m != nil {
		return m.MutiStoreTree
	}
	return MutiStoreTreeFields{}
}

func (m *QueryMultistoreResponse) GetIavl() []IAVLMerklePathEvm {
	if m != nil {
		return m.Iavl
	}
	return nil
}

type QueryInclusionProofRequest struct {
	Height    int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Qid       string `protobuf:"bytes,2,opt,name=qid,proto3" json:"qid,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *QueryInclusionProofRequest) Reset()         { *m = QueryInclusionProofRequest{} }
func (m *QueryInclusionProofRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInclusionProofRequest) ProtoMessage()    {}
func (*QueryInclusionProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{5}
}
func (m *QueryInclusionProofRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInclusionProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInclusionProofRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInclusionProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInclusionProofRequest.Merge(m, src)
}
func (m *QueryInclusionProofRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInclusionProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInclusionProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInclusionProofRequest proto.InternalMessageInfo

func (m *QueryInclusionProofRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *QueryInclusionProofRequest) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func (m *QueryInclusionProofRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type QueryInclusionProofResponse struct {
	InclusionProofStuff InclusionProofStuffFields `protobuf:"bytes,1,opt,name=InclusionProofStuff,proto3" json:"InclusionProofStuff"`
	MerklePath          []IAVLMerklePathEvm       `protobuf:"bytes,2,rep,name=MerklePath,proto3" json:"MerklePath"`
}

func (m *QueryInclusionProofResponse) Reset()         { *m = QueryInclusionProofResponse{} }
func (m *QueryInclusionProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInclusionProofResponse) ProtoMessage()    {}
func (*QueryInclusionProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{6}
}
func (m *QueryInclusionProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInclusionProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInclusionProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInclusionProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInclusionProofResponse.Merge(m, src)
}
func (m *QueryInclusionProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInclusionProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInclusionProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInclusionProofResponse proto.InternalMessageInfo

func (m *QueryInclusionProofResponse) GetInclusionProofStuff() InclusionProofStuffFields {
	if m != nil {
		return m.InclusionProofStuff
	}
	return InclusionProofStuffFields{}
}

func (m *QueryInclusionProofResponse) GetMerklePath() []IAVLMerklePathEvm {
	if m != nil {
		return m.MerklePath
	}
	return nil
}

type QueryTmRequest struct {
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryTmRequest) Reset()         { *m = QueryTmRequest{} }
func (m *QueryTmRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTmRequest) ProtoMessage()    {}
func (*QueryTmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{7}
}
func (m *QueryTmRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTmRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTmRequest.Merge(m, src)
}
func (m *QueryTmRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTmRequest proto.InternalMessageInfo

func (m *QueryTmRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type QueryTmResponse struct {
	TmSig  []TmSig               `protobuf:"bytes,1,rep,name=tmSig,proto3" json:"tmSig"`
	Common CommonEncodedVotePart `protobuf:"bytes,2,opt,name=common,proto3" json:"common"`
}

func (m *QueryTmResponse) Reset()         { *m = QueryTmResponse{} }
func (m *QueryTmResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTmResponse) ProtoMessage()    {}
func (*QueryTmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b20ab372cf6c0d8e, []int{8}
}
func (m *QueryTmResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTmResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTmResponse.Merge(m, src)
}
func (m *QueryTmResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTmResponse proto.InternalMessageInfo

func (m *QueryTmResponse) GetTmSig() []TmSig {
	if m != nil {
		return m.TmSig
	}
	return nil
}

func (m *QueryTmResponse) GetCommon() CommonEncodedVotePart {
	if m != nil {
		return m.Common
	}
	return CommonEncodedVotePart{}
}

func init() {
	proto.RegisterType((*QueryBlockheaderMerkleRequest)(nil), "luqchain.bridge.QueryBlockheaderMerkleRequest")
	proto.RegisterType((*QueryBlockheaderMerkleResponse)(nil), "luqchain.bridge.QueryBlockheaderMerkleResponse")
	proto.RegisterType((*QueryBlockheaderMerkleEVMResponse)(nil), "luqchain.bridge.QueryBlockheaderMerkleEVMResponse")
	proto.RegisterType((*QueryMultistoreRequest)(nil), "luqchain.bridge.QueryMultistoreRequest")
	proto.RegisterType((*QueryMultistoreResponse)(nil), "luqchain.bridge.QueryMultistoreResponse")
	proto.RegisterType((*QueryInclusionProofRequest)(nil), "luqchain.bridge.QueryInclusionProofRequest")
	proto.RegisterType((*QueryInclusionProofResponse)(nil), "luqchain.bridge.QueryInclusionProofResponse")
	proto.RegisterType((*QueryTmRequest)(nil), "luqchain.bridge.QueryTmRequest")
	proto.RegisterType((*QueryTmResponse)(nil), "luqchain.bridge.QueryTmResponse")
}

func init() { proto.RegisterFile("luqchain/bridge/services.proto", fileDescriptor_b20ab372cf6c0d8e) }

var fileDescriptor_b20ab372cf6c0d8e = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x4f, 0xdb, 0x4a,
	0x10, 0xce, 0x12, 0x88, 0xc4, 0xa0, 0x07, 0x8f, 0x7d, 0x28, 0x2f, 0x32, 0x60, 0x82, 0x0b, 0x25,
	0xd0, 0x36, 0x96, 0xd2, 0x43, 0x2f, 0xbd, 0x34, 0x6d, 0x2a, 0x90, 0x1a, 0x29, 0x0d, 0x28, 0x87,
	0x5e, 0xa8, 0x13, 0x2f, 0xce, 0x16, 0xdb, 0x1b, 0xec, 0x75, 0xd4, 0x5e, 0xab, 0x1e, 0x2a, 0xf5,
	0x52, 0xa9, 0xfd, 0x01, 0xbd, 0xf2, 0x4f, 0x90, 0x7a, 0x41, 0xea, 0xa5, 0xa7, 0xaa, 0x82, 0xf6,
	0x7f, 0x54, 0x59, 0x6f, 0x12, 0x62, 0x1b, 0x02, 0x52, 0x6f, 0xb6, 0xe7, 0x9b, 0x6f, 0xbe, 0xf9,
	0xbc, 0x33, 0x0b, 0xaa, 0x1d, 0x1c, 0xb5, 0xda, 0x06, 0x75, 0xf5, 0xa6, 0x47, 0x4d, 0x8b, 0xe8,
	0x3e, 0xf1, 0xba, 0xb4, 0x45, 0xfc, 0x62, 0xc7, 0x63, 0x9c, 0xe1, 0xb9, 0x7e, 0xbc, 0x18, 0xc6,
	0x95, 0x05, 0x8b, 0x59, 0x4c, 0xc4, 0xf4, 0xde, 0x53, 0x08, 0x53, 0x96, 0x2c, 0xc6, 0x2c, 0x9b,
	0xe8, 0x46, 0x87, 0xea, 0x86, 0xeb, 0x32, 0x6e, 0x70, 0xca, 0x5c, 0x49, 0xa2, 0x6c, 0x46, 0x8b,
	0x34, 0x6d, 0xd6, 0x3a, 0xdc, 0x6f, 0x13, 0xc3, 0x24, 0xde, 0xbe, 0x43, 0xbc, 0x43, 0x9b, 0x48,
	0x68, 0x3e, 0x0a, 0x75, 0x02, 0x9b, 0x53, 0x9f, 0x33, 0xaf, 0x8f, 0x58, 0x8c, 0x22, 0xb8, 0xe3,
	0x53, 0x4b, 0x06, 0xd7, 0xa2, 0x41, 0xea, 0xb6, 0xec, 0xc0, 0xa7, 0xcc, 0xed, 0x78, 0x8c, 0x1d,
	0x84, 0x28, 0xed, 0x01, 0x2c, 0x3f, 0x0f, 0x88, 0xf7, 0xa6, 0xdc, 0x93, 0x11, 0xaa, 0xa8, 0x0a,
	0x11, 0x75, 0x72, 0x14, 0x10, 0x9f, 0xe3, 0x2c, 0x64, 0xda, 0x84, 0x5a, 0x6d, 0x9e, 0x43, 0x79,
	0x54, 0x48, 0xd7, 0xe5, 0x9b, 0xf6, 0x1a, 0xd4, 0xcb, 0x12, 0xfd, 0x0e, 0x73, 0x7d, 0x82, 0x1b,
	0x30, 0xdf, 0x8c, 0x06, 0x05, 0xc9, 0x4c, 0x49, 0x2b, 0x46, 0xbc, 0x2c, 0x0a, 0x9a, 0xed, 0x0b,
	0xc8, 0xf2, 0xe4, 0xc9, 0x8f, 0x95, 0x54, 0x3d, 0x4e, 0xa1, 0xbd, 0x43, 0xb0, 0x9a, 0x5c, 0xba,
	0xd2, 0xa8, 0x0e, 0xaa, 0xef, 0xc3, 0x42, 0x2c, 0xb5, 0xd2, 0x75, 0xa4, 0x80, 0xf5, 0xf1, 0x02,
	0x2a, 0x5d, 0x47, 0x6a, 0x48, 0x24, 0xd2, 0x5e, 0x42, 0x56, 0xa8, 0xa8, 0x0e, 0xfe, 0xca, 0x18,
	0xcb, 0xf0, 0xbf, 0x90, 0x3e, 0xa2, 0x66, 0x6e, 0x22, 0x8f, 0x0a, 0xd3, 0xf5, 0xde, 0x23, 0x5e,
	0x82, 0x69, 0x4e, 0x1d, 0xe2, 0x73, 0xc3, 0xe9, 0xe4, 0xd2, 0x79, 0x54, 0x98, 0xac, 0x0f, 0x3f,
	0x68, 0xc7, 0x08, 0xfe, 0x8f, 0x95, 0x90, 0xed, 0xd5, 0xe0, 0x9f, 0x6a, 0xc0, 0xe9, 0x6e, 0xef,
	0xe3, 0x9e, 0x47, 0xfa, 0xc6, 0xae, 0xc5, 0xfa, 0x1a, 0x41, 0x3d, 0xa5, 0xc4, 0x36, 0x7d, 0xd9,
	0xd6, 0x28, 0x01, 0x7e, 0x08, 0x93, 0xd4, 0xe8, 0xda, 0xb9, 0x89, 0x7c, 0x3a, 0xf1, 0x0f, 0xed,
	0x3c, 0x6a, 0x3c, 0x0b, 0xbb, 0xaf, 0x19, 0xbc, 0x3d, 0x74, 0x47, 0x64, 0x69, 0x26, 0x28, 0x42,
	0xea, 0x4e, 0xff, 0x90, 0xd5, 0x7a, 0x87, 0xec, 0x6f, 0x3b, 0xf2, 0x15, 0xc1, 0x62, 0x62, 0x19,
	0xe9, 0x4a, 0x13, 0xfe, 0x1b, 0x8d, 0xec, 0xf2, 0xe0, 0xe0, 0x40, 0x7a, 0xb3, 0x15, 0x6f, 0x29,
	0x8e, 0x1d, 0x71, 0x28, 0x89, 0x0c, 0x6f, 0x03, 0x0c, 0x6d, 0xb8, 0xb1, 0x5b, 0x17, 0x72, 0xb5,
	0x02, 0xcc, 0x8a, 0x66, 0xf6, 0x9c, 0x71, 0xc3, 0xf6, 0x01, 0xc1, 0xdc, 0x00, 0x2a, 0x7b, 0x2d,
	0xc1, 0x14, 0x77, 0x76, 0xa9, 0x95, 0x43, 0x42, 0x42, 0x36, 0x26, 0x61, 0xaf, 0x17, 0x95, 0x65,
	0x43, 0x28, 0x7e, 0x02, 0x99, 0x16, 0x73, 0x1c, 0xe6, 0x0a, 0xcb, 0x67, 0x4a, 0xb7, 0x63, 0x49,
	0x8f, 0x45, 0xb8, 0xe2, 0xb6, 0x98, 0x49, 0xcc, 0x06, 0xe3, 0xa4, 0x66, 0x78, 0x5c, 0x92, 0xc8,
	0xdc, 0xd2, 0xef, 0x29, 0xc8, 0x94, 0x05, 0x1c, 0x7f, 0x41, 0x30, 0x1f, 0x1b, 0x43, 0x5c, 0x8c,
	0xd1, 0x5e, 0xb9, 0x63, 0x14, 0xfd, 0xda, 0xf8, 0xb0, 0x77, 0x6d, 0xeb, 0xed, 0xb7, 0x5f, 0x9f,
	0x26, 0xd6, 0xb0, 0xa6, 0x27, 0xae, 0xd3, 0x30, 0x27, 0x5c, 0xa6, 0xf8, 0x18, 0xc1, 0x42, 0xd2,
	0xa6, 0xb8, 0xb1, 0xca, 0xd2, 0x35, 0xf1, 0x17, 0xb6, 0x90, 0x76, 0x4f, 0x08, 0xdd, 0xc0, 0xeb,
	0xe3, 0x85, 0x92, 0xae, 0x83, 0xdf, 0x23, 0x98, 0x1d, 0x0e, 0xbb, 0x18, 0xcb, 0x8d, 0xe4, 0xaa,
	0xb1, 0xad, 0xa3, 0x14, 0xc6, 0x03, 0xa5, 0xa8, 0x5b, 0x42, 0xd4, 0x32, 0x5e, 0xd4, 0x2f, 0xbf,
	0x61, 0xf0, 0x2b, 0x98, 0x12, 0x07, 0x08, 0xaf, 0x24, 0xf3, 0x0e, 0x0e, 0xad, 0x92, 0xbf, 0x1c,
	0x20, 0x0b, 0xaa, 0xa2, 0x60, 0x0e, 0x67, 0xf5, 0xc4, 0x0b, 0x0b, 0x7f, 0x46, 0x30, 0x3b, 0x3a,
	0x6a, 0xf8, 0x4e, 0x32, 0x69, 0xe2, 0x7a, 0x51, 0xee, 0x5e, 0x0f, 0x2c, 0xd5, 0x6c, 0x08, 0x35,
	0xab, 0x78, 0x45, 0xbf, 0xfa, 0x86, 0x2c, 0x6f, 0x9e, 0x9c, 0xa9, 0xe8, 0xf4, 0x4c, 0x45, 0x3f,
	0xcf, 0x54, 0xf4, 0xf1, 0x5c, 0x4d, 0x9d, 0x9e, 0xab, 0xa9, 0xef, 0xe7, 0x6a, 0xea, 0xc5, 0x5c,
	0x24, 0xb3, 0x99, 0x11, 0xb7, 0xe9, 0xfd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xee, 0xeb,
	0x00, 0x44, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BridgeClient interface {
	BlockheaderMerkle(ctx context.Context, in *QueryBlockheaderMerkleRequest, opts ...grpc.CallOption) (*QueryBlockheaderMerkleResponse, error)
	BlockheaderMerkleEVM(ctx context.Context, in *QueryBlockheaderMerkleRequest, opts ...grpc.CallOption) (*QueryBlockheaderMerkleEVMResponse, error)
	MultistoreTree(ctx context.Context, in *QueryMultistoreRequest, opts ...grpc.CallOption) (*QueryMultistoreResponse, error)
	TmSig(ctx context.Context, in *QueryTmRequest, opts ...grpc.CallOption) (*QueryTmResponse, error)
	InclusionProof(ctx context.Context, in *QueryInclusionProofRequest, opts ...grpc.CallOption) (*QueryInclusionProofResponse, error)
}

type bridgeClient struct {
	cc grpc1.ClientConn
}

func NewBridgeClient(cc grpc1.ClientConn) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) BlockheaderMerkle(ctx context.Context, in *QueryBlockheaderMerkleRequest, opts ...grpc.CallOption) (*QueryBlockheaderMerkleResponse, error) {
	out := new(QueryBlockheaderMerkleResponse)
	err := c.cc.Invoke(ctx, "/luqchain.bridge.Bridge/BlockheaderMerkle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) BlockheaderMerkleEVM(ctx context.Context, in *QueryBlockheaderMerkleRequest, opts ...grpc.CallOption) (*QueryBlockheaderMerkleEVMResponse, error) {
	out := new(QueryBlockheaderMerkleEVMResponse)
	err := c.cc.Invoke(ctx, "/luqchain.bridge.Bridge/BlockheaderMerkleEVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) MultistoreTree(ctx context.Context, in *QueryMultistoreRequest, opts ...grpc.CallOption) (*QueryMultistoreResponse, error) {
	out := new(QueryMultistoreResponse)
	err := c.cc.Invoke(ctx, "/luqchain.bridge.Bridge/MultistoreTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) TmSig(ctx context.Context, in *QueryTmRequest, opts ...grpc.CallOption) (*QueryTmResponse, error) {
	out := new(QueryTmResponse)
	err := c.cc.Invoke(ctx, "/luqchain.bridge.Bridge/TmSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) InclusionProof(ctx context.Context, in *QueryInclusionProofRequest, opts ...grpc.CallOption) (*QueryInclusionProofResponse, error) {
	out := new(QueryInclusionProofResponse)
	err := c.cc.Invoke(ctx, "/luqchain.bridge.Bridge/InclusionProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServer is the server API for Bridge service.
type BridgeServer interface {
	BlockheaderMerkle(context.Context, *QueryBlockheaderMerkleRequest) (*QueryBlockheaderMerkleResponse, error)
	BlockheaderMerkleEVM(context.Context, *QueryBlockheaderMerkleRequest) (*QueryBlockheaderMerkleEVMResponse, error)
	MultistoreTree(context.Context, *QueryMultistoreRequest) (*QueryMultistoreResponse, error)
	TmSig(context.Context, *QueryTmRequest) (*QueryTmResponse, error)
	InclusionProof(context.Context, *QueryInclusionProofRequest) (*QueryInclusionProofResponse, error)
}

// UnimplementedBridgeServer can be embedded to have forward compatible implementations.
type UnimplementedBridgeServer struct {
}

func (*UnimplementedBridgeServer) BlockheaderMerkle(ctx context.Context, req *QueryBlockheaderMerkleRequest) (*QueryBlockheaderMerkleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockheaderMerkle not implemented")
}
func (*UnimplementedBridgeServer) BlockheaderMerkleEVM(ctx context.Context, req *QueryBlockheaderMerkleRequest) (*QueryBlockheaderMerkleEVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockheaderMerkleEVM not implemented")
}
func (*UnimplementedBridgeServer) MultistoreTree(ctx context.Context, req *QueryMultistoreRequest) (*QueryMultistoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultistoreTree not implemented")
}
func (*UnimplementedBridgeServer) TmSig(ctx context.Context, req *QueryTmRequest) (*QueryTmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TmSig not implemented")
}
func (*UnimplementedBridgeServer) InclusionProof(ctx context.Context, req *QueryInclusionProofRequest) (*QueryInclusionProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InclusionProof not implemented")
}

func RegisterBridgeServer(s grpc1.Server, srv BridgeServer) {
	s.RegisterService(&_Bridge_serviceDesc, srv)
}

func _Bridge_BlockheaderMerkle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlockheaderMerkleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).BlockheaderMerkle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luqchain.bridge.Bridge/BlockheaderMerkle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).BlockheaderMerkle(ctx, req.(*QueryBlockheaderMerkleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_BlockheaderMerkleEVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlockheaderMerkleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).BlockheaderMerkleEVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luqchain.bridge.Bridge/BlockheaderMerkleEVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).BlockheaderMerkleEVM(ctx, req.(*QueryBlockheaderMerkleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_MultistoreTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMultistoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).MultistoreTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luqchain.bridge.Bridge/MultistoreTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).MultistoreTree(ctx, req.(*QueryMultistoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_TmSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).TmSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luqchain.bridge.Bridge/TmSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).TmSig(ctx, req.(*QueryTmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_InclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).InclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luqchain.bridge.Bridge/InclusionProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).InclusionProof(ctx, req.(*QueryInclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bridge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luqchain.bridge.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlockheaderMerkle",
			Handler:    _Bridge_BlockheaderMerkle_Handler,
		},
		{
			MethodName: "BlockheaderMerkleEVM",
			Handler:    _Bridge_BlockheaderMerkleEVM_Handler,
		},
		{
			MethodName: "MultistoreTree",
			Handler:    _Bridge_MultistoreTree_Handler,
		},
		{
			MethodName: "TmSig",
			Handler:    _Bridge_TmSig_Handler,
		},
		{
			MethodName: "InclusionProof",
			Handler:    _Bridge_InclusionProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "luqchain/bridge/services.proto",
}

func (m *QueryBlockheaderMerkleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBlockheaderMerkleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBlockheaderMerkleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBlockheaderMerkleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBlockheaderMerkleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBlockheaderMerkleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BlockheaderMerkle.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServices(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBlockheaderMerkleEVMResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBlockheaderMerkleEVMResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBlockheaderMerkleEVMResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BlockheaderMerkleEvm.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServices(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMultistoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultistoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultistoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Qid) > 0 {
		i -= len(m.Qid)
		copy(dAtA[i:], m.Qid)
		i = encodeVarintServices(dAtA, i, uint64(len(m.Qid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryMultistoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMultistoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMultistoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Iavl) > 0 {
		for iNdEx := len(m.Iavl) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Iavl[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintServices(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.MutiStoreTree.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServices(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInclusionProofRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInclusionProofRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInclusionProofRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Qid) > 0 {
		i -= len(m.Qid)
		copy(dAtA[i:], m.Qid)
		i = encodeVarintServices(dAtA, i, uint64(len(m.Qid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryInclusionProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInclusionProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInclusionProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MerklePath) > 0 {
		for iNdEx := len(m.MerklePath) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MerklePath[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintServices(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.InclusionProofStuff.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServices(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTmRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTmRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTmRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintServices(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTmResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTmResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Common.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintServices(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.TmSig) > 0 {
		for iNdEx := len(m.TmSig) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TmSig[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintServices(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintServices(dAtA []byte, offset int, v uint64) int {
	offset -= sovServices(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryBlockheaderMerkleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovServices(uint64(m.Height))
	}
	return n
}

func (m *QueryBlockheaderMerkleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BlockheaderMerkle.Size()
	n += 1 + l + sovServices(uint64(l))
	return n
}

func (m *QueryBlockheaderMerkleEVMResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BlockheaderMerkleEvm.Size()
	n += 1 + l + sovServices(uint64(l))
	return n
}

func (m *QueryMultistoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovServices(uint64(m.Height))
	}
	l = len(m.Qid)
	if l > 0 {
		n += 1 + l + sovServices(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovServices(uint64(m.Timestamp))
	}
	return n
}

func (m *QueryMultistoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MutiStoreTree.Size()
	n += 1 + l + sovServices(uint64(l))
	if len(m.Iavl) > 0 {
		for _, e := range m.Iavl {
			l = e.Size()
			n += 1 + l + sovServices(uint64(l))
		}
	}
	return n
}

func (m *QueryInclusionProofRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovServices(uint64(m.Height))
	}
	l = len(m.Qid)
	if l > 0 {
		n += 1 + l + sovServices(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovServices(uint64(m.Timestamp))
	}
	return n
}

func (m *QueryInclusionProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InclusionProofStuff.Size()
	n += 1 + l + sovServices(uint64(l))
	if len(m.MerklePath) > 0 {
		for _, e := range m.MerklePath {
			l = e.Size()
			n += 1 + l + sovServices(uint64(l))
		}
	}
	return n
}

func (m *QueryTmRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovServices(uint64(m.Height))
	}
	return n
}

func (m *QueryTmResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TmSig) > 0 {
		for _, e := range m.TmSig {
			l = e.Size()
			n += 1 + l + sovServices(uint64(l))
		}
	}
	l = m.Common.Size()
	n += 1 + l + sovServices(uint64(l))
	return n
}

func sovServices(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServices(x uint64) (n int) {
	return sovServices(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryBlockheaderMerkleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBlockheaderMerkleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockheaderMerkle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockheaderMerkle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBlockheaderMerkleEVMResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleEVMResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBlockheaderMerkleEVMResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockheaderMerkleEvm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockheaderMerkleEvm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultistoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultistoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultistoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Qid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Qid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMultistoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMultistoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMultistoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutiStoreTree", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutiStoreTree.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iavl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Iavl = append(m.Iavl, IAVLMerklePathEvm{})
			if err := m.Iavl[len(m.Iavl)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInclusionProofRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInclusionProofRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInclusionProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Qid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Qid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInclusionProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInclusionProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInclusionProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InclusionProofStuff", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InclusionProofStuff.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerklePath", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerklePath = append(m.MerklePath, IAVLMerklePathEvm{})
			if err := m.MerklePath[len(m.MerklePath)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTmRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTmRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTmRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServices
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TmSig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TmSig = append(m.TmSig, TmSig{})
			if err := m.TmSig[len(m.TmSig)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Common", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServices
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServices
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServices
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Common.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServices(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServices
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServices(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServices
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServices
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServices
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServices
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServices
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServices
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServices        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServices          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServices = fmt.Errorf("proto: unexpected end of group")
)
